TestWEB/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace TestWEB.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TestWEB/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestWEB.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

TestWEB/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestWEB.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TestWEB/Pages/SomeRemoteCalls.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestWEB.Pages
{
    public class SomeRemoteCallsModel : PageModel
    {
        private static readonly HttpClient client = new HttpClient();

        //private static string reqUrl = "https://testshopapi.azurewebsites.net/api/LongExecution/longexecution";
        //private static string reqUrl2 = "https://testshopapi.azurewebsites.net/api/exception/throwexception";
        //private static string reqUrl3 = "https://testshopapi.azurewebsites.net/api/LongExecution/DoubleHop";
        //private static string reqUrl4 = "https://testshopapi.azurewebsites.net/api/LongExecution/ChattyDoubleHop";

        private static string reqUrl = Environment.GetEnvironmentVariable("TestShopApi_LongExecution"); 
        private static string reqUrl2 = Environment.GetEnvironmentVariable("TestShopApi_ThrowException"); 
        private static string reqUrl3 = Environment.GetEnvironmentVariable("TestShopApi_DoubleHop"); 
        private static string reqUrl4 = Environment.GetEnvironmentVariable("TestShopApi_ChattyDoubleHop"); 

        public void OnGet()
        {
        }
        
        public void OnPostCallALongFunction()
        {
            var result = client.GetStringAsync(reqUrl).Result;
            return;
        }

        public void OnPostCallAnExceptionFunction()
        {
            var result = client.GetStringAsync(reqUrl2).Result;
            return;
        }

        public void OnPostCallaDoubleHopFunction()
        {
            var result = client.GetStringAsync(reqUrl3).Result;
            return;
        }

        public void OnPostCallaChattyFunction()
        {
            var result = client.GetStringAsync(reqUrl4).Result;
            return;
        }


    }
}

TestWEB/Pages/WeatherForecastCall.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;
using TestWEB.Lib;

namespace TestWEB.Pages
{
    public class WheatherForecastCallModel : PageModel
    {
        private static readonly HttpClient client = new HttpClient();

        private static string reqUrl = "https://testshopapi.azurewebsites.net/weatherforecast";

        public IList<WeatherForecast>? Forecasts { get; set; }

        private static async Task<List<WeatherForecast>> GetForecasts()

        {

            List<WeatherForecast> fcs = new List<WeatherForecast>();

            var streamTask = await client.GetStreamAsync(reqUrl);

            await foreach (var fc in JsonSerializer.DeserializeAsyncEnumerable<WeatherForecast>(streamTask))

                fcs.Add(fc);

            return fcs;

        }

        public bool gfcWrapper()

        {

            Forecasts = GetForecasts().Result;

            if (Forecasts == null)

                return false;

            else

                return true;

        }
        public void OnGet()
        {
            gfcWrapper();
        }
    }
}

TestWEB/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TestWEB/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestWEB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">TestWEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/WeatherForecastCall">Weather forecast call</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/SomeRemoteCalls">Test various remote calls</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Wait">Test various waits</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TestWEB - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TestWEB/Pages/SomeRemoteCalls.cshtml
@page
@model TestWEB.Pages.SomeRemoteCallsModel
@{
}

<form method="post" asp-page-handler="CallALongFunction">
    <button>Call a long executing function</button>
</form>

<form method="post" asp-page-handler="CallAnExceptionFunction">
    <button>Call a function that throws an exception</button>
</form>

<form method="post" asp-page-handler="CallaDoubleHopFunction">
    <button>Call a function that calls another remote function</button>
</form>

<form method="post" asp-page-handler="CallaChattyFunction">
    <button>Call a chatty function</button>
</form>

TestWEB/Pages/WeatherForecastCall.cshtml
@page
@model TestWEB.Pages.WheatherForecastCallModel
@{
}

<table class="table">

    <thead>
        <tr>
            <th>Date</th>
            <th>Feels</th>
            <th>TempF</th>
            <th>TempC</th>
        </tr>
    </thead>

    <tbody>
        @if (Model.Forecasts != null)
        {
            foreach (var forecast in Model.Forecasts)
            {
                <tr>
                    <td> @forecast.date</td>
                    <td> @forecast.summary</td>
                    <td> @forecast.temperatureF</td>
                    <td> @forecast.temperatureC</td>
                </tr>
            }
        }
    </tbody>

</table>